# このバージョンがインストールされているかどうかを処理の判定基準とする
virtualbox_version: 6.1.6
# VBoxGuestAdditions_{{ virtualbox_version }}.isoファイルのチェックサム（http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/SHA256SUMS）
iso_checksum: "sha256:bcde4691dea7de93b65a10a43dda2b8f52e570f820992ad281c9bb5c8dede181"
# isoファイルのダウンロードディレクトリ
iso_download_path: "/opt/vboxguest"
# isoファイルのマウントパス
iso_mount_path: /mnt/virtualbox
# isoファイルのダウンロード先パス
virtualbox_iso_path: "{{iso_download_path}}/VBoxGuestAdditions_{{virtualbox_version}}.iso"
# x11ありでインストールする場合に変数と値を定義しておく
virtualbox_x11: true