all:
  hosts:
    mk-vm-centos7-01:
      ansible_port: 50023
      ansible_host: localhost
    mk-vm-centos8-01:
      ansible_port: 50025
      ansible_host: localhost
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/ssh_private_key_for_ansible
