- name: "日本語設定 | 日本語関連のパッケージをインストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  yum:
    name:
      - ibus-kkc
      - vlgothic-*
    state: present

- name: "日本語設定 | システムの文字セットを変更する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      localectl set-locale LANG=ja_JP.UTF-8
      source /etc/locale.conf

- name: "日本語設定 | ibusデーモンの自動起動設定ファイルを配置する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  copy:
    src: ibus_auto_start
    dest: "{{ ibus.auto_start.file.path }}"
    owner: root
    group: root
    mode: '0755'

- name: "日本語設定 | ibusデーモンの自動起動設定ファイルをロードする"
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      cat ~/.bashrc | grep ". {{ ibus.auto_start.file.path }}" >/dev/null
      if [ $? -eq 0 ]; then
        echo "already changed."
      else
        echo -e "\n. {{ ibus.auto_start.file.path }}" >> ~/.bashrc
        source ~/.bashrc
      fi
